title: jesusaguilera.com
job: Software Engineer
company: Capital Insurance Group
description: >-
  Dev
author: Jesus Aguilera

# jekyll-paginate cofiguration
paginate: 5

# Build settings
markdown: kramdown
highligher: rouge
permalink: none
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
  style: :nested
