title: jesusaguilera.com
job: Software Engineer I
company: Capital Insurance Group
description: >-
  My passion is working to provide a service that will help thousands of people by pushing buttons on a keyboard.
author: Jesus Aguilera

# jekyll-paginate cofiguration
paginate: 5

# Build settings
markdown: kramdown
highligher: rouge
permalink: none
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
  style: :nested
