title: jeaguil.dev
job: Software Developer
author: jeg

# Build settings
markdown: kramdown
highligher: rouge
permalink: none
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
  style: :nested