title: Jeaguil.net
author: Jesus Aguilera
email: jesus.aguilera3401@gmail.com
url: https://jeaguil.net
baseurl: ""
description: >
  

favicon: "favicon.ico"

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
