menu:
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

resource:
- {name: 'Tech blogs', folder: 'pages', file: 'techblogs.html'}
- {name: 'Learning Resources', folder: 'pages', file: 'learning-resources.html'}

# Available social icons are powered by Font Awesome
social:
- {icon: 'github', link: 'https://github.com/jeaguil'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jesuscmaguilera/'}
- {icon: 'envelope', link: 'mailto:jesus.aguilera3401@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

post_date_prefix: 'Written on'
